# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='meal',
            new_name='meals',
        ),
    ]
