# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170815_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Card'),
        ),
    ]
