# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170815_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='card',
        ),
        migrations.AddField(
            model_name='meal',
            name='card',
            field=models.ManyToManyField(blank=True, null=True, to='menu.Card'),
        ),
    ]
