# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20170815_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='card',
            field=models.ManyToManyField(blank=True, to='menu.Card'),
        ),
    ]
