# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20170815_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='picture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
