# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_meal_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='meal',
            field=models.ManyToManyField(blank=True, to='menu.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='picture',
            field=models.ImageField(null=True, upload_to='menu/static/menu/pictures'),
        ),
    ]
